#!/usr/bin/env python3
"""Generate website publication and selected invited talk pages from CV data."""

from __future__ import annotations

import argparse
import datetime as dt
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
sys.path.insert(0, str(SCRIPT_DIR))

from cv_data import BibEntry, load_bib_entries, load_yaml_list  # noqa: E402
from generate_cv_publications import classify_entries, format_authors, sort_section  # noqa: E402


DEFAULT_BIB = Path("data/publications.bib")
DEFAULT_TALKS = Path("data/talks.yml")
DEFAULT_HOME_PAGE = Path("_pages/about.md")
DEFAULT_PUBLICATIONS_PAGE = Path("_pages/publications.md")
DEFAULT_TALKS_PAGE = Path("_pages/talks.md")

BEGIN_MARKER = "<!-- BEGIN GENERATED CV WEBSITE CONTENT -->"
END_MARKER = "<!-- END GENERATED CV WEBSITE CONTENT -->"
GENERATED_COMMENT = "<!-- This section is generated by scripts/generate_site_pages.py. Do not edit manually. -->"


@dataclass(frozen=True)
class PublicationSections:
    preprints: list[BibEntry]
    publications: list[BibEntry]
    manual_reviews: list[str]


@dataclass(frozen=True)
class TalkGroup:
    group: dict[str, Any]
    title: str | None
    appearances: list[dict[str, Any]]


@dataclass(frozen=True)
class GenerationResult:
    bib_path: Path
    talks_path: Path
    home_page: Path
    publications_page: Path
    talks_page: Path
    preprint_count: int
    publication_count: int
    manual_review_count: int
    selected_talk_group_count: int
    selected_talk_appearance_count: int


def repo_path(path: Path) -> Path:
    return path if path.is_absolute() else REPO_ROOT / path


def markdown_text(value: str | None) -> str:
    if not value:
        return ""
    text = value.replace(r"\&", "&")
    text = text.replace("{", "").replace("}", "")
    text = text.replace("--", "-")
    return re.sub(r"\s+", " ", text).strip()


def highlight_author_name(authors: str) -> str:
    return re.sub(r"\bJingyang Li\b", "**Jingyang Li**", authors)


def arxiv_id(entry: BibEntry) -> str | None:
    haystack = " ".join(
        entry.fields.get(name, "")
        for name in ("journal", "eprint", "archiveprefix", "url", "doi", "note")
    )
    match = re.search(r"arxiv\s*:?\s*(\d{4}\.\d{4,5}(?:v\d+)?)", haystack, flags=re.IGNORECASE)
    return match.group(1) if match else None


def format_links(entry: BibEntry) -> str:
    links: list[str] = []
    arxiv = arxiv_id(entry)
    if arxiv:
        links.append(f"[[arXiv]](https://arxiv.org/abs/{arxiv})")

    doi = markdown_text(entry.fields.get("doi"))
    if doi:
        doi_url = doi if doi.startswith(("http://", "https://")) else f"https://doi.org/{doi}"
        links.append(f"[[DOI]]({doi_url})")

    url = markdown_text(entry.fields.get("url"))
    if url and all(url not in link for link in links):
        label = "Link"
        if "doi.org" in url:
            label = "DOI"
        elif "arxiv.org" in url:
            label = "arXiv"
        links.append(f"[[{label}]]({url})")

    return " " + ", ".join(links) if links else ""


def format_venue(entry: BibEntry) -> str:
    journal = markdown_text(entry.fields.get("journal"))
    note = markdown_text(entry.fields.get("note"))
    year = markdown_text(entry.fields.get("year"))
    volume = markdown_text(entry.fields.get("volume"))
    number = markdown_text(entry.fields.get("number"))
    pages = markdown_text(entry.fields.get("pages"))

    pieces: list[str] = []
    if journal:
        pieces.append(f"*{journal}*")

    volume_text = ""
    if volume and number:
        volume_text = f"{volume}({number})"
    elif volume:
        volume_text = volume
    elif number:
        volume_text = f"({number})"

    details = [piece for piece in (volume_text, pages, year) if piece]
    if details:
        pieces.append(", ".join(details))
    elif year:
        pieces.append(year)

    if note:
        pieces.append(note)

    return ", ".join(pieces)


def format_publication_entry(entry: BibEntry) -> str:
    title = markdown_text(entry.fields.get("title"))
    authors = highlight_author_name(markdown_text(format_authors(entry.fields.get("author", ""))))
    venue = format_venue(entry)
    links = format_links(entry)

    lines = [f"1. **{title}**<br>"]
    if authors:
        lines.append(f"   {authors}.<br>")
    if venue or links:
        lines.append(f"   {venue}{links}.")
    return "\n".join(lines)


def render_publication_sections(sections: PublicationSections) -> str:
    lines: list[str] = [GENERATED_COMMENT, "", "Publications", "======", ""]
    for entry in sections.publications:
        lines.extend([format_publication_entry(entry), ""])

    lines.extend(["Preprints", "======", ""])
    for entry in sections.preprints:
        lines.extend([format_publication_entry(entry), ""])

    if sections.manual_reviews:
        lines.extend(["<!-- Manual review needed before website display:"])
        lines.extend(f"- {item}" for item in sections.manual_reviews)
        lines.append("-->")

    return "\n".join(lines).rstrip()


def load_publication_sections(bib_path: Path, current_year: int) -> tuple[Path, PublicationSections]:
    resolved_bib_path, entries = load_bib_entries(bib_path)
    preprints, publications, manual_reviews = classify_entries(entries)
    sections = PublicationSections(
        preprints=sort_section(preprints, "preprints", current_year),
        publications=sort_section(publications, "publications", current_year),
        manual_reviews=[
            f"{review.key}: {markdown_text(review.title)} ({review.reason})" for review in manual_reviews
        ],
    )
    return resolved_bib_path, sections


def group_label(group: dict[str, Any]) -> str:
    return markdown_text(
        str(group.get("display_label") or group.get("paper_title") or group.get("paper_key") or "Untitled work")
    )


def truthy(value: Any) -> bool:
    return value is True


def selected_appearances(group: dict[str, Any]) -> list[dict[str, Any]]:
    if not truthy(group.get("include_in_cv")):
        return []
    return [appearance for appearance in group.get("appearances", []) if truthy(appearance.get("invited"))]


def talk_group_title(group: dict[str, Any], bib_titles: dict[str, str]) -> str | None:
    paper_key = group.get("paper_key")
    if paper_key and paper_key in bib_titles:
        return markdown_text(bib_titles[paper_key])
    if group.get("paper_title"):
        return markdown_text(str(group["paper_title"]))
    if group.get("display_label"):
        return None
    return group_label(group)


def format_talk_appearance(appearance: dict[str, Any]) -> str:
    pieces = [
        markdown_text(str(appearance.get("venue", ""))),
        markdown_text(str(appearance.get("session", ""))),
        markdown_text(str(appearance.get("location", ""))),
        markdown_text(str(appearance.get("date", ""))),
    ]
    main = ", ".join(piece for piece in pieces if piece)

    talk_type = markdown_text(str(appearance.get("type", "")))
    if talk_type:
        main = f"{main} (*{talk_type}*)"

    url = markdown_text(str(appearance.get("url", "")))
    if url:
        main = f"{main} [[link]]({url})"

    return main


def load_talk_groups(talks_path: Path, bib_titles: dict[str, str]) -> list[TalkGroup]:
    groups = load_yaml_list(talks_path)
    selected: list[TalkGroup] = []
    for group in groups:
        appearances = selected_appearances(group)
        if not appearances:
            continue
        selected.append(TalkGroup(group=group, title=talk_group_title(group, bib_titles), appearances=appearances))
    return selected


def render_talk_sections(talk_groups: list[TalkGroup], include_heading: bool = True) -> str:
    lines: list[str] = [GENERATED_COMMENT, ""]
    if include_heading:
        lines.extend(["Selected Invited Talks", "======"])

    for talk_group in talk_groups:
        if talk_group.title:
            lines.append(f"**Related paper:** *{talk_group.title}*")
        else:
            lines.append(f"**Research topic:** *{group_label(talk_group.group)}*")

        for appearance in talk_group.appearances:
            lines.append(f"- {format_talk_appearance(appearance)}")
        lines.append("")

    return "\n".join(lines).rstrip()


def front_matter(title: str, permalink: str) -> str:
    return (
        "---\n"
        "layout: archive\n"
        f'title: "{title}"\n'
        f"permalink: {permalink}\n"
        "author_profile: true\n"
        "---\n"
    )


def write_generated_page(path: Path, title: str, permalink: str, body: str) -> None:
    path.write_text(f"{front_matter(title, permalink)}\n{body}\n", encoding="utf-8")


def update_home_page(path: Path, generated_body: str) -> None:
    original = path.read_text(encoding="utf-8")
    replacement = f"{BEGIN_MARKER}\n{generated_body}\n{END_MARKER}"

    if BEGIN_MARKER in original and END_MARKER in original:
        updated = re.sub(
            rf"{re.escape(BEGIN_MARKER)}.*?{re.escape(END_MARKER)}",
            replacement,
            original,
            flags=re.DOTALL,
        )
        path.write_text(updated.rstrip() + "\n", encoding="utf-8")
        return

    heading_positions = [
        pos
        for heading in ("Preprints\n======", "Publications\n======", "Selected Invited Talks\n======")
        if (pos := original.find(heading)) != -1
    ]
    contact_match = re.search(r"\nContact\n=+\n", original)

    if heading_positions:
        start = min(heading_positions)
    elif contact_match:
        start = contact_match.start() + 1
    else:
        start = len(original)

    if contact_match and contact_match.start() > start:
        end = contact_match.start() + 1
        suffix = original[end:].lstrip()
    else:
        end = len(original)
        suffix = original[end:].lstrip()

    prefix = original[:start].rstrip()
    updated = f"{prefix}\n\n{replacement}\n"
    if suffix:
        updated += f"\n{suffix.rstrip()}\n"
    path.write_text(updated, encoding="utf-8")


def generate_site_pages(
    bib: Path = DEFAULT_BIB,
    talks: Path = DEFAULT_TALKS,
    home_page: Path = DEFAULT_HOME_PAGE,
    publications_page: Path = DEFAULT_PUBLICATIONS_PAGE,
    talks_page: Path = DEFAULT_TALKS_PAGE,
    current_year: int | None = None,
) -> GenerationResult:
    if current_year is None:
        current_year = dt.date.today().year

    bib_path = repo_path(bib)
    talks_path = repo_path(talks)
    home_path = repo_path(home_page)
    publications_path = repo_path(publications_page)
    talks_output_path = repo_path(talks_page)

    resolved_bib_path, publication_sections = load_publication_sections(bib_path, current_year)
    _, entries = load_bib_entries(resolved_bib_path)
    bib_titles = {entry.key: entry.fields.get("title", "") for entry in entries}
    talk_groups = load_talk_groups(talks_path, bib_titles)

    publications_body = render_publication_sections(publication_sections)
    talks_body = render_talk_sections(talk_groups)
    talks_page_body = render_talk_sections(talk_groups, include_heading=False)

    update_home_page(home_path, f"{publications_body}\n\n{talks_body}")
    write_generated_page(publications_path, "Publications and Preprints", "/publications/", publications_body)
    write_generated_page(talks_output_path, "Selected Invited Talks", "/talks/", talks_page_body)

    return GenerationResult(
        bib_path=resolved_bib_path,
        talks_path=talks_path,
        home_page=home_path,
        publications_page=publications_path,
        talks_page=talks_output_path,
        preprint_count=len(publication_sections.preprints),
        publication_count=len(publication_sections.publications),
        manual_review_count=len(publication_sections.manual_reviews),
        selected_talk_group_count=len(talk_groups),
        selected_talk_appearance_count=sum(len(group.appearances) for group in talk_groups),
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bib", type=Path, default=DEFAULT_BIB, help="Canonical BibTeX source.")
    parser.add_argument("--talks", type=Path, default=DEFAULT_TALKS, help="Canonical talks YAML source.")
    parser.add_argument("--home-page", type=Path, default=DEFAULT_HOME_PAGE, help="Homepage markdown path.")
    parser.add_argument("--publications-page", type=Path, default=DEFAULT_PUBLICATIONS_PAGE)
    parser.add_argument("--talks-page", type=Path, default=DEFAULT_TALKS_PAGE)
    parser.add_argument("--current-year", type=int, default=dt.date.today().year)
    args = parser.parse_args()

    result = generate_site_pages(
        bib=args.bib,
        talks=args.talks,
        home_page=args.home_page,
        publications_page=args.publications_page,
        talks_page=args.talks_page,
        current_year=args.current_year,
    )

    print(f"Publications source: {result.bib_path.relative_to(REPO_ROOT)}")
    print(f"Talks source: {result.talks_path.relative_to(REPO_ROOT)}")
    print(f"Homepage updated: {result.home_page.relative_to(REPO_ROOT)}")
    print(f"Publications page updated: {result.publications_page.relative_to(REPO_ROOT)}")
    print(f"Talks page updated: {result.talks_page.relative_to(REPO_ROOT)}")
    print(f"Preprints generated: {result.preprint_count}")
    print(f"Publications generated: {result.publication_count}")
    print(f"Selected invited talk groups generated: {result.selected_talk_group_count}")
    print(f"Selected invited talk appearances generated: {result.selected_talk_appearance_count}")
    if result.manual_review_count:
        print(f"Manual publication review items omitted: {result.manual_review_count}")
    else:
        print("Manual publication review items omitted: none")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
