#!/usr/bin/env python3
"""Generate the teaching website page and CV section from data/teaching.yml."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from cv_data import escape_latex, load_yaml_list, write_text


DEFAULT_INPUT = Path("data/teaching.yml")
DEFAULT_CV_OUTPUT = Path("Resume/cv/generated/teaching.tex")
DEFAULT_SITE_OUTPUT = Path("_pages/teaching.md")


@dataclass(frozen=True)
class TeachingGenerationResult:
    input_path: Path
    cv_output_path: Path
    site_output_path: Path
    group_count: int
    course_count: int


def text(value: Any) -> str:
    return str(value or "").strip()


def courses_for_group(group: dict[str, Any]) -> list[dict[str, Any]]:
    courses = group.get("courses", [])
    if not isinstance(courses, list):
        raise ValueError(f"{text(group.get('institution')) or 'Teaching group'}: courses must be a list")
    return courses


def validate_groups(groups: list[dict[str, Any]]) -> None:
    for group in groups:
        institution = text(group.get("institution"))
        role = text(group.get("role"))
        if not institution:
            raise ValueError("Each teaching group needs an institution")
        if not role:
            raise ValueError(f"{institution}: missing role")

        for course in courses_for_group(group):
            if not text(course.get("title")) and not text(course.get("site_title")):
                raise ValueError(f"{institution}: each course needs title or site_title")


def cv_course_label(group: dict[str, Any], course: dict[str, Any]) -> str:
    explicit = text(course.get("cv_label"))
    if explicit:
        return explicit

    title = text(course.get("cv_title")) or text(course.get("title")) or text(course.get("site_title"))
    role = text(course.get("cv_role")) or text(course.get("role")) or text(group.get("role"))
    years = text(course.get("years")) or text(course.get("term"))

    label = title
    if role:
        label = f"{label} ({role})"
    if years:
        label = f"{label}, {years}"
    return label


def site_course_label(course: dict[str, Any]) -> str:
    label = text(course.get("site_title")) or text(course.get("title"))
    date = text(course.get("term")) or text(course.get("years"))
    if date:
        return f"{label} ({date})"
    return label


def render_cv_section(input_path: Path, groups: list[dict[str, Any]]) -> str:
    lines = [
        "% This file is generated by scripts/generate_teaching.py.",
        f"% Source data file: {input_path.as_posix()}",
        "% Do not edit this file manually; update data/teaching.yml and rerun the generator.",
        "",
        r"\vspace{5pt}",
        r"\section{Teaching}",
        r"\begin{itemize}[leftmargin=*]",
    ]

    for group in groups:
        for course in courses_for_group(group):
            lines.append(rf"  \item {{{escape_latex(cv_course_label(group, course))}}}")

    lines.append(r"\end{itemize}")
    lines.append("")
    return "\n".join(lines)


def render_site_page(groups: list[dict[str, Any]]) -> str:
    lines = [
        "---",
        "layout: archive",
        'title: "Teaching Experience"',
        "permalink: /teaching/",
        "author_profile: true",
        "---",
        "",
        "<!-- This section is generated by scripts/generate_teaching.py. Do not edit manually. -->",
        "",
    ]

    for index, group in enumerate(groups):
        if index:
            lines.append("")

        institution = text(group.get("institution"))
        role = text(group.get("site_role")) or text(group.get("role"))
        heading = f"{institution}, {role}" if role else institution
        lines.append(f"**{heading}**")
        for course in courses_for_group(group):
            lines.append(f"- {site_course_label(course)}")

    lines.append("")
    return "\n".join(lines)


def generate_teaching(
    input_path: Path = DEFAULT_INPUT,
    cv_output_path: Path = DEFAULT_CV_OUTPUT,
    site_output_path: Path = DEFAULT_SITE_OUTPUT,
) -> TeachingGenerationResult:
    groups = load_yaml_list(input_path)
    validate_groups(groups)

    write_text(cv_output_path, render_cv_section(input_path, groups))
    write_text(site_output_path, render_site_page(groups))

    return TeachingGenerationResult(
        input_path=input_path,
        cv_output_path=cv_output_path,
        site_output_path=site_output_path,
        group_count=len(groups),
        course_count=sum(len(courses_for_group(group)) for group in groups),
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT, help="Path to teaching YAML data.")
    parser.add_argument("--cv-output", type=Path, default=DEFAULT_CV_OUTPUT, help="Generated CV LaTeX output path.")
    parser.add_argument("--site-output", type=Path, default=DEFAULT_SITE_OUTPUT, help="Generated website page path.")
    args = parser.parse_args()

    result = generate_teaching(args.input, args.cv_output, args.site_output)
    print(f"Input file: {result.input_path}")
    print(f"CV output file: {result.cv_output_path}")
    print(f"Website output file: {result.site_output_path}")
    print(f"Teaching groups: {result.group_count}")
    print(f"Courses: {result.course_count}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
